FROM golang:1.20.6-bullseye

WORKDIR /usr/src/app

COPY go.mod .
COPY go.sum .
RUN go mod download && go mod verify

COPY . .

RUN go build -v -o /usr/local/bin/grpc-server ./cmd/grpc-server

CMD ["grpc-server"]
